name=LoadingLCD
version=1.0.0
author=Igor Macedo
maintainer=Igor Macedo <iglmacedo@gmail.com>
sentence=An animated LCD loading sequence library.
paragraph=This library provides custom loading animations for LCDs using createChar and write.
category=Display
url=https://github.com/Igor-Leonor-Macedo/LoadingLCD
architectures=*
